source BCS_DSSD_noise-gate.tcl

filter -new noise-filter any_good {bdecay.front.hiecal.01
                                   bdecay.front.hiecal.02
                                   bdecay.front.hiecal.03
                                   bdecay.front.hiecal.04
                                   bdecay.front.hiecal.05
                                   bdecay.front.hiecal.06
                                   bdecay.front.hiecal.07
                                   bdecay.front.hiecal.08
                                   bdecay.front.hiecal.09
                                   bdecay.front.hiecal.10
                                   bdecay.front.hiecal.11
                                   bdecay.front.hiecal.12
                                   bdecay.front.hiecal.13
                                   bdecay.front.hiecal.14
                                   bdecay.front.hiecal.15
                                   bdecay.front.hiecal.16
                                   bdecay.front.hiecal.17
                                   bdecay.front.hiecal.18
                                   bdecay.front.hiecal.19
                                   bdecay.front.hiecal.20
                                   bdecay.front.hiecal.21
                                   bdecay.front.hiecal.22
                                   bdecay.front.hiecal.23
                                   bdecay.front.hiecal.24
                                   bdecay.front.hiecal.25
                                   bdecay.front.hiecal.26
                                   bdecay.front.hiecal.27
                                   bdecay.front.hiecal.28
                                   bdecay.front.hiecal.29
                                   bdecay.front.hiecal.30
                                   bdecay.front.hiecal.31
                                   bdecay.front.hiecal.32
                                   bdecay.front.hiecal.33
                                   bdecay.front.hiecal.34
                                   bdecay.front.hiecal.35
                                   bdecay.front.hiecal.36
                                   bdecay.front.hiecal.37
                                   bdecay.front.hiecal.38
                                   bdecay.front.hiecal.39
                                   bdecay.front.hiecal.40
                                   bdecay.back.hiecal.01
                                   bdecay.back.hiecal.02
                                   bdecay.back.hiecal.03
                                   bdecay.back.hiecal.04
                                   bdecay.back.hiecal.05
                                   bdecay.back.hiecal.06
                                   bdecay.back.hiecal.07
                                   bdecay.back.hiecal.08
                                   bdecay.back.hiecal.09
                                   bdecay.back.hiecal.10
                                   bdecay.back.hiecal.11
                                   bdecay.back.hiecal.12
                                   bdecay.back.hiecal.13
                                   bdecay.back.hiecal.14
                                   bdecay.back.hiecal.15
                                   bdecay.back.hiecal.16
                                   bdecay.back.hiecal.17
                                   bdecay.back.hiecal.18
                                   bdecay.back.hiecal.19
                                   bdecay.back.hiecal.20
                                   bdecay.back.hiecal.21
                                   bdecay.back.hiecal.22
                                   bdecay.back.hiecal.23
                                   bdecay.back.hiecal.24
                                   bdecay.back.hiecal.25
                                   bdecay.back.hiecal.26
                                   bdecay.back.hiecal.27
                                   bdecay.back.hiecal.28
                                   bdecay.back.hiecal.29
                                   bdecay.back.hiecal.30
                                   bdecay.back.hiecal.31
                                   bdecay.back.hiecal.32
                                   bdecay.back.hiecal.33
                                   bdecay.back.hiecal.34
                                   bdecay.back.hiecal.35
                                   bdecay.back.hiecal.36
                                   bdecay.back.hiecal.37
                                   bdecay.back.hiecal.38
                                   bdecay.back.hiecal.39
                                   bdecay.back.hiecal.40}

filter -enable noise-filter 
