swrite -format ascii NEROSpectra/NEROQuadA01 NERO\ Quad\ A\ Ch01
swrite -format ascii NEROSpectra/NEROQuadA02 NERO\ Quad\ A\ Ch02
swrite -format ascii NEROSpectra/NEROQuadA03 NERO\ Quad\ A\ Ch03
swrite -format ascii NEROSpectra/NEROQuadA04 NERO\ Quad\ A\ Ch04
swrite -format ascii NEROSpectra/NEROQuadA05 NERO\ Quad\ A\ Ch05
swrite -format ascii NEROSpectra/NEROQuadA06 NERO\ Quad\ A\ Ch06
swrite -format ascii NEROSpectra/NEROQuadA07 NERO\ Quad\ A\ Ch07
swrite -format ascii NEROSpectra/NEROQuadA08 NERO\ Quad\ A\ Ch08
swrite -format ascii NEROSpectra/NEROQuadA09 NERO\ Quad\ A\ Ch09
swrite -format ascii NEROSpectra/NEROQuadA10 NERO\ Quad\ A\ Ch10
swrite -format ascii NEROSpectra/NEROQuadA11 NERO\ Quad\ A\ Ch11
swrite -format ascii NEROSpectra/NEROQuadA12 NERO\ Quad\ A\ Ch12
swrite -format ascii NEROSpectra/NEROQuadA13 NERO\ Quad\ A\ Ch13
swrite -format ascii NEROSpectra/NEROQuadA14 NERO\ Quad\ A\ Ch14
swrite -format ascii NEROSpectra/NEROQuadA15 NERO\ Quad\ A\ Ch15
swrite -format ascii NEROSpectra/NEROQuadD01 NERO\ Quad\ D\ Ch01
swrite -format ascii NEROSpectra/NEROQuadD02 NERO\ Quad\ D\ Ch02
swrite -format ascii NEROSpectra/NEROQuadD03 NERO\ Quad\ D\ Ch03
swrite -format ascii NEROSpectra/NEROQuadD04 NERO\ Quad\ D\ Ch04
swrite -format ascii NEROSpectra/NEROQuadD05 NERO\ Quad\ D\ Ch05
swrite -format ascii NEROSpectra/NEROQuadD06 NERO\ Quad\ D\ Ch06
swrite -format ascii NEROSpectra/NEROQuadD07 NERO\ Quad\ D\ Ch07
swrite -format ascii NEROSpectra/NEROQuadD08 NERO\ Quad\ D\ Ch08
swrite -format ascii NEROSpectra/NEROQuadD09 NERO\ Quad\ D\ Ch09
swrite -format ascii NEROSpectra/NEROQuadD10 NERO\ Quad\ D\ Ch10
swrite -format ascii NEROSpectra/NEROQuadD11 NERO\ Quad\ D\ Ch11
swrite -format ascii NEROSpectra/NEROQuadD12 NERO\ Quad\ D\ Ch12
swrite -format ascii NEROSpectra/NEROQuadD13 NERO\ Quad\ D\ Ch13
swrite -format ascii NEROSpectra/NEROQuadD14 NERO\ Quad\ D\ Ch14
swrite -format ascii NEROSpectra/NEROQuadD15 NERO\ Quad\ D\ Ch15
